if __name__ == "__main__":

    import ROOT
    import argparse

    fW=ROOT.TFile("files_nominal/QCD.root","r")
    fW_jfru=ROOT.TFile("files_nominal/QCD_wup.root","r")
    fW_jfrd=ROOT.TFile("files_nominal/QCD_wdown.root","r")
    fout_jfru=ROOT.TFile("files_nominal/QCD_wup_norm.root","recreate")
    fout_jfrd=ROOT.TFile("files_nominal/QCD_wdown_norm.root","recreate")

    hW00jet=fW.Get("mt_0jet/QCD")
    hW00jet_u=fW_jfru.Get("mt_0jet/QCD_WSFUncert_mt_0jet_13TeVUp")
    hW00jet_d=fW_jfrd.Get("mt_0jet/QCD_WSFUncert_mt_0jet_13TeVDown")
    hW00jet_u.Scale(hW00jet.Integral()/hW00jet_u.Integral())
    hW00jet_d.Scale(hW00jet.Integral()/hW00jet_d.Integral())

    hW11jet=fW.Get("mt_boosted/QCD")
    hW11jet_u=fW_jfru.Get("mt_boosted/QCD_WSFUncert_mt_boosted_13TeVUp")
    hW11jet_d=fW_jfrd.Get("mt_boosted/QCD_WSFUncert_mt_boosted_13TeVDown")
    hW11jet_u.Scale(hW11jet.Integral()/hW11jet_u.Integral())
    hW11jet_d.Scale(hW11jet.Integral()/hW11jet_d.Integral())

    hW0jet=fW.Get("mt_vbf_D0_0p0to0p2/QCD")
    hW0jet_u=fW_jfru.Get("mt_vbf_D0_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW0jet_d=fW_jfrd.Get("mt_vbf_D0_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW0jet_u.Scale(hW0jet.Integral()/hW0jet_u.Integral())
    hW0jet_d.Scale(hW0jet.Integral()/hW0jet_d.Integral())

    hW1jet=fW.Get("mt_vbf_D0_0p2to0p4/QCD")
    hW1jet_u=fW_jfru.Get("mt_vbf_D0_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW1jet_d=fW_jfrd.Get("mt_vbf_D0_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW1jet_u.Scale(hW1jet.Integral()/hW1jet_u.Integral())
    hW1jet_d.Scale(hW1jet.Integral()/hW1jet_d.Integral())

    hW2jet=fW.Get("mt_vbf_D0_0p4to0p8/QCD")
    hW2jet_u=fW_jfru.Get("mt_vbf_D0_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW2jet_d=fW_jfrd.Get("mt_vbf_D0_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW2jet_u.Scale(hW2jet.Integral()/hW2jet_u.Integral())
    hW2jet_d.Scale(hW2jet.Integral()/hW2jet_d.Integral())

    hW4jet=fW.Get("mt_vbf_D0_0p8to1p0/QCD")
    hW4jet_u=fW_jfru.Get("mt_vbf_D0_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW4jet_d=fW_jfrd.Get("mt_vbf_D0_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW4jet_u.Scale(hW4jet.Integral()/hW4jet_u.Integral())
    hW4jet_d.Scale(hW4jet.Integral()/hW4jet_d.Integral())

    hW70jet=fW.Get("mt_vbf_D0hplus_0p0to0p2/QCD")
    hW70jet_u=fW_jfru.Get("mt_vbf_D0hplus_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW70jet_d=fW_jfrd.Get("mt_vbf_D0hplus_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW70jet_u.Scale(hW70jet.Integral()/hW70jet_u.Integral())
    hW70jet_d.Scale(hW70jet.Integral()/hW70jet_d.Integral())

    hW71jet=fW.Get("mt_vbf_D0hplus_0p2to0p4/QCD")
    hW71jet_u=fW_jfru.Get("mt_vbf_D0hplus_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW71jet_d=fW_jfrd.Get("mt_vbf_D0hplus_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW71jet_u.Scale(hW71jet.Integral()/hW71jet_u.Integral())
    hW71jet_d.Scale(hW71jet.Integral()/hW71jet_d.Integral())

    hW72jet=fW.Get("mt_vbf_D0hplus_0p4to0p8/QCD")
    hW72jet_u=fW_jfru.Get("mt_vbf_D0hplus_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW72jet_d=fW_jfrd.Get("mt_vbf_D0hplus_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW72jet_u.Scale(hW72jet.Integral()/hW72jet_u.Integral())
    hW72jet_d.Scale(hW72jet.Integral()/hW72jet_d.Integral())

    hW74jet=fW.Get("mt_vbf_D0hplus_0p8to1p0/QCD")
    hW74jet_u=fW_jfru.Get("mt_vbf_D0hplus_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW74jet_d=fW_jfrd.Get("mt_vbf_D0hplus_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW74jet_u.Scale(hW74jet.Integral()/hW74jet_u.Integral())
    hW74jet_d.Scale(hW74jet.Integral()/hW74jet_d.Integral())

    hW80jet=fW.Get("mt_vbf_DL1_0p0to0p2/QCD")
    hW80jet_u=fW_jfru.Get("mt_vbf_DL1_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW80jet_d=fW_jfrd.Get("mt_vbf_DL1_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW80jet_u.Scale(hW80jet.Integral()/hW80jet_u.Integral())
    hW80jet_d.Scale(hW80jet.Integral()/hW80jet_d.Integral())

    hW81jet=fW.Get("mt_vbf_DL1_0p2to0p4/QCD")
    hW81jet_u=fW_jfru.Get("mt_vbf_DL1_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW81jet_d=fW_jfrd.Get("mt_vbf_DL1_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW81jet_u.Scale(hW81jet.Integral()/hW81jet_u.Integral())
    hW81jet_d.Scale(hW81jet.Integral()/hW81jet_d.Integral())

    hW82jet=fW.Get("mt_vbf_DL1_0p4to0p8/QCD")
    hW82jet_u=fW_jfru.Get("mt_vbf_DL1_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW82jet_d=fW_jfrd.Get("mt_vbf_DL1_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW82jet_u.Scale(hW82jet.Integral()/hW82jet_u.Integral())
    hW82jet_d.Scale(hW82jet.Integral()/hW82jet_d.Integral())

    hW84jet=fW.Get("mt_vbf_DL1_0p8to1p0/QCD")
    hW84jet_u=fW_jfru.Get("mt_vbf_DL1_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW84jet_d=fW_jfrd.Get("mt_vbf_DL1_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW84jet_u.Scale(hW84jet.Integral()/hW84jet_u.Integral())
    hW84jet_d.Scale(hW84jet.Integral()/hW84jet_d.Integral())

    hW90jet=fW.Get("mt_vbf_DL1Zg_0p0to0p2/QCD")
    hW90jet_u=fW_jfru.Get("mt_vbf_DL1Zg_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW90jet_d=fW_jfrd.Get("mt_vbf_DL1Zg_0p0to0p2/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW90jet_u.Scale(hW90jet.Integral()/hW90jet_u.Integral())
    hW90jet_d.Scale(hW90jet.Integral()/hW90jet_d.Integral())

    hW91jet=fW.Get("mt_vbf_DL1Zg_0p2to0p4/QCD")
    hW91jet_u=fW_jfru.Get("mt_vbf_DL1Zg_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW91jet_d=fW_jfrd.Get("mt_vbf_DL1Zg_0p2to0p4/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW91jet_u.Scale(hW91jet.Integral()/hW91jet_u.Integral())
    hW91jet_d.Scale(hW91jet.Integral()/hW91jet_d.Integral())

    hW92jet=fW.Get("mt_vbf_DL1Zg_0p4to0p8/QCD")
    hW92jet_u=fW_jfru.Get("mt_vbf_DL1Zg_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW92jet_d=fW_jfrd.Get("mt_vbf_DL1Zg_0p4to0p8/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW92jet_u.Scale(hW92jet.Integral()/hW92jet_u.Integral())
    hW92jet_d.Scale(hW92jet.Integral()/hW92jet_d.Integral())

    hW94jet=fW.Get("mt_vbf_DL1Zg_0p8to1p0/QCD")
    hW94jet_u=fW_jfru.Get("mt_vbf_DL1Zg_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVUp")
    hW94jet_d=fW_jfrd.Get("mt_vbf_DL1Zg_0p8to1p0/QCD_WSFUncert_mt_vbf_13TeVDown")
    hW94jet_u.Scale(hW94jet.Integral()/hW94jet_u.Integral())
    hW94jet_d.Scale(hW94jet.Integral()/hW94jet_d.Integral())


    fout_jfru.cd()

    dir00OS=fout_jfru.mkdir("mt_0jet")
    dir00OS.cd()
    hW00jet_u.SetName("QCD_WSFUncert_mt_0jet_13TeVUp")
    hW00jet_u.Write()
    hW00jet_d.SetName("QCD_WSFUncert_mt_0jet_13TeVDown")
    hW00jet_d.Write()

    dir11OS=fout_jfru.mkdir("mt_boosted")
    dir11OS.cd()
    hW11jet_u.SetName("QCD_WSFUncert_mt_boosted_13TeVUp")
    hW11jet_u.Write()
    hW11jet_d.SetName("QCD_WSFUncert_mt_boosted_13TeVDown")
    hW11jet_d.Write()

    dir0OS=fout_jfru.mkdir("mt_vbf_D0_0p0to0p2")
    dir0OS.cd()
    hW0jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW0jet_u.Write()
    hW0jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW0jet_d.Write()

    dir1OS=fout_jfru.mkdir("mt_vbf_D0_0p2to0p4")
    dir1OS.cd()
    hW1jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW1jet_u.Write()
    hW1jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW1jet_d.Write()

    dir2OS=fout_jfru.mkdir("mt_vbf_D0_0p4to0p8")
    dir2OS.cd()
    hW2jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW2jet_u.Write()
    hW2jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW2jet_d.Write()

    dir4OS=fout_jfru.mkdir("mt_vbf_D0_0p8to1p0")
    dir4OS.cd()
    hW4jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW4jet_u.Write()
    hW4jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW4jet_d.Write()

    dir70OS=fout_jfru.mkdir("mt_vbf_D0hplus_0p0to0p2")
    dir70OS.cd()
    hW70jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW70jet_u.Write()
    hW70jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW70jet_d.Write()

    dir71OS=fout_jfru.mkdir("mt_vbf_D0hplus_0p2to0p4")
    dir71OS.cd()
    hW71jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW71jet_u.Write()
    hW71jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW71jet_d.Write()

    dir72OS=fout_jfru.mkdir("mt_vbf_D0hplus_0p4to0p8")
    dir72OS.cd()
    hW72jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW72jet_u.Write()
    hW72jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW72jet_d.Write()

    dir74OS=fout_jfru.mkdir("mt_vbf_D0hplus_0p8to1p0")
    dir74OS.cd()
    hW74jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW74jet_u.Write()
    hW74jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW74jet_d.Write()

    dir80OS=fout_jfru.mkdir("mt_vbf_DL1_0p0to0p2")
    dir80OS.cd()
    hW80jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW80jet_u.Write()
    hW80jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW80jet_d.Write()

    dir81OS=fout_jfru.mkdir("mt_vbf_DL1_0p2to0p4")
    dir81OS.cd()
    hW81jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW81jet_u.Write()
    hW81jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW81jet_d.Write()

    dir82OS=fout_jfru.mkdir("mt_vbf_DL1_0p4to0p8")
    dir82OS.cd()
    hW82jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW82jet_u.Write()
    hW82jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW82jet_d.Write()

    dir84OS=fout_jfru.mkdir("mt_vbf_DL1_0p8to1p0")
    dir84OS.cd()
    hW84jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW84jet_u.Write()
    hW84jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW84jet_d.Write()

    dir90OS=fout_jfru.mkdir("mt_vbf_DL1Zg_0p0to0p2")
    dir90OS.cd()
    hW90jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW90jet_u.Write()
    hW90jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW90jet_d.Write()

    dir91OS=fout_jfru.mkdir("mt_vbf_DL1Zg_0p2to0p4")
    dir91OS.cd()
    hW91jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW91jet_u.Write()
    hW91jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW91jet_d.Write()

    dir92OS=fout_jfru.mkdir("mt_vbf_DL1Zg_0p4to0p8")
    dir92OS.cd()
    hW92jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW92jet_u.Write()
    hW92jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW92jet_d.Write()

    dir94OS=fout_jfru.mkdir("mt_vbf_DL1Zg_0p8to1p0")
    dir94OS.cd()
    hW94jet_u.SetName("QCD_WSFUncert_mt_vbf_13TeVUp")
    hW94jet_u.Write()
    hW94jet_d.SetName("QCD_WSFUncert_mt_vbf_13TeVDown")
    hW94jet_d.Write()

